# Generated by Django 4.2.7 on 2023-12-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mascota_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='descripción',
            field=models.CharField(max_length=500, verbose_name='Descripción'),
        ),
    ]
